name: setup playwright test demo 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test-DEV:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: checkout  code
        uses: actions/checkout@v4
      
      - name: setup nodejs
        uses: actions/setup-node@v4

      - name: install dependencies
        run: npm install

      - name: install playwright browsers
        run: npx playwright install --with-deps

      - name: run tests
        run: npx playwright test loginpage.spec.ts 

      - name: upload playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: /playwright-report


